sudo: false
dist: trusty
language: java
script: mvn clean install
matrix:
  include:
    - env: JDK_RELEASE='OracleJDK 8'
      jdk: oraclejdk8
      deploy:
        provider: pages
        skip-cleanup: true
        repo: modcluster/docs.modcluster.io
        local-dir: docs/target/generated-docs/
        target-branch: gh-pages
        keep-history: true
        github-token: $GITHUB_TOKEN
        committer-from-gh: true
        email: docs-bot@modcluster.io
        allow-empty-commit: false
        verbose: true
        on:
          branch: master
